source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'bazdig-toolkit-ios_Example', :exclusive => true do
  pod 'bazdig-toolkit-ios', :path => '../'
end

target 'bazdig-toolkit-ios_Tests', :exclusive => true do
  pod 'bazdig-toolkit-ios', :path => '../'

  
end
